version: '3.9'

services:
  db_khanto:
    container_name: DB_khanto
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5435:5432"
    networks:
      - production-network
    expose:
      - 5432

  api:
    build:
      dockerfile: docker/api.dockerfile
      context: .
    container_name: api_khanto
    command: >
      sh -c " python manage.py makemigrations
              python manage.py migrate sites
              python manage.py migrate
              python manage.py collectstatic
              python manage.py loaddata fixtures/*.json 
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8083:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY='this-is-a-secret-key'
    depends_on:
      - db_khanto
    networks:
      - production-network
    restart: on-failure:30

volumes:
  postgres_data:

networks:
  production-network:
    driver: bridge
